---
version: '3.8'

services:
  nginx:
    env_file:
      - docker/defaults.env
      - docker/local.env
    environment:
      - USE_LETS_ENCRYPT=false
  application:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "3000:3000"
    volumes:
      - ..:/srv/primero/application
      - /srv/primero/application/config
      - /srv/primero/application/public
      - storage:/srv/primero/application/storage
  solr:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "8983:8983"
  beanstalkd:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "11300:11300"
  backburner:
    env_file:
      - docker/defaults.env
      - docker/local.env
  postgres:
    env_file:
      - docker/defaults.env
      - docker/local.env
    ports:
      - "5432:5432"
  scheduler:
    env_file:
      - docker/defaults.env
      - docker/local.env
